
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hivemq-cluster
  name: hivemq-hpa
  namespace: hivemq
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: hivemq-replica
  targetCPUUtilizationPercentage: 80